[package]
name = "rpi_fanctrl"
version = "1.0.0"
edition = "2021"

[dependencies]
rppal = "0.22.1"
ctrlc = "3.4.5"
dotenvy = "0.15.7"
chrono = "0.4.39"
csv = "1.3.1"
signal-hook = "0.3.17"

[profile.dev]
panic = "abort"
lto = "fat"

[profile.release]
panic = "abort"
lto = "fat"